
package at.ac.tuwien.swa.service.peerservice;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "PeerService", targetNamespace = "http://PeerService.service.swa.tuwien.ac.at/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface PeerService {


    /**
     * 
     * @param arg0
     * @return
     *     returns at.ac.tuwien.swa.service.peerservice.AnalysisResult
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "checkFingerprint", targetNamespace = "http://PeerService.service.swa.tuwien.ac.at/", className = "at.ac.tuwien.swa.service.peerservice.CheckFingerprint")
    @ResponseWrapper(localName = "checkFingerprintResponse", targetNamespace = "http://PeerService.service.swa.tuwien.ac.at/", className = "at.ac.tuwien.swa.service.peerservice.CheckFingerprintResponse")
    @Action(input = "http://PeerService.service.swa.tuwien.ac.at/PeerService/checkFingerprintRequest", output = "http://PeerService.service.swa.tuwien.ac.at/PeerService/checkFingerprintResponse")
    public AnalysisResult checkFingerprint(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

}
