
package at.ac.tuwien.swa.service.serverservice;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ServerService", targetNamespace = "http://ServerService.service.swa.tuwien.ac.at/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ServerService {


    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "disconnectPeer", targetNamespace = "http://ServerService.service.swa.tuwien.ac.at/", className = "at.ac.tuwien.swa.service.serverservice.DisconnectPeer")
    @ResponseWrapper(localName = "disconnectPeerResponse", targetNamespace = "http://ServerService.service.swa.tuwien.ac.at/", className = "at.ac.tuwien.swa.service.serverservice.DisconnectPeerResponse")
    @Action(input = "http://ServerService.service.swa.tuwien.ac.at/ServerService/disconnectPeerRequest", output = "http://ServerService.service.swa.tuwien.ac.at/ServerService/disconnectPeerResponse")
    public String disconnectPeer(
        @WebParam(name = "arg0", targetNamespace = "")
        PeerInformation arg0);

    /**
     * 
     * @return
     *     returns at.ac.tuwien.swa.service.serverservice.PeerInformation
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getRandomPeer", targetNamespace = "http://ServerService.service.swa.tuwien.ac.at/", className = "at.ac.tuwien.swa.service.serverservice.GetRandomPeer")
    @ResponseWrapper(localName = "getRandomPeerResponse", targetNamespace = "http://ServerService.service.swa.tuwien.ac.at/", className = "at.ac.tuwien.swa.service.serverservice.GetRandomPeerResponse")
    @Action(input = "http://ServerService.service.swa.tuwien.ac.at/ServerService/getRandomPeerRequest", output = "http://ServerService.service.swa.tuwien.ac.at/ServerService/getRandomPeerResponse")
    public PeerInformation getRandomPeer();

    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "connectPeer", targetNamespace = "http://ServerService.service.swa.tuwien.ac.at/", className = "at.ac.tuwien.swa.service.serverservice.ConnectPeer")
    @ResponseWrapper(localName = "connectPeerResponse", targetNamespace = "http://ServerService.service.swa.tuwien.ac.at/", className = "at.ac.tuwien.swa.service.serverservice.ConnectPeerResponse")
    @Action(input = "http://ServerService.service.swa.tuwien.ac.at/ServerService/connectPeerRequest", output = "http://ServerService.service.swa.tuwien.ac.at/ServerService/connectPeerResponse")
    public String connectPeer(
        @WebParam(name = "arg0", targetNamespace = "")
        PeerInformation arg0);

    /**
     * 
     * @return
     *     returns at.ac.tuwien.swa.service.serverservice.PeerInformation
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getRelayPeer", targetNamespace = "http://ServerService.service.swa.tuwien.ac.at/", className = "at.ac.tuwien.swa.service.serverservice.GetRelayPeer")
    @ResponseWrapper(localName = "getRelayPeerResponse", targetNamespace = "http://ServerService.service.swa.tuwien.ac.at/", className = "at.ac.tuwien.swa.service.serverservice.GetRelayPeerResponse")
    @Action(input = "http://ServerService.service.swa.tuwien.ac.at/ServerService/getRelayPeerRequest", output = "http://ServerService.service.swa.tuwien.ac.at/ServerService/getRelayPeerResponse")
    public PeerInformation getRelayPeer();

    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "registerPeer", targetNamespace = "http://ServerService.service.swa.tuwien.ac.at/", className = "at.ac.tuwien.swa.service.serverservice.RegisterPeer")
    @ResponseWrapper(localName = "registerPeerResponse", targetNamespace = "http://ServerService.service.swa.tuwien.ac.at/", className = "at.ac.tuwien.swa.service.serverservice.RegisterPeerResponse")
    @Action(input = "http://ServerService.service.swa.tuwien.ac.at/ServerService/registerPeerRequest", output = "http://ServerService.service.swa.tuwien.ac.at/ServerService/registerPeerResponse")
    public String registerPeer(
        @WebParam(name = "arg0", targetNamespace = "")
        PeerInformation arg0);

}
